### ISSUE TITLE
ENV files incorrectly referenced

### ISSUE THREAD

**Issue by chrisvanderpoel** [Abodeo/laravel-stripe#10]
Environment configuration files (`.env.local.php`, for example) are having their contents referenced incorrectly based on a Laravel 4.2 install.

Currently, Stripe credentials are being referenced like this:

    isset($_ENV['stripe']['publishable_key'])

... in `LaravelStripeServiceProvider.php` when, in fact, they should be referenced like this...

    isset($_ENV['stripe.publishable_key'])

This is due to the fact that Laravel 4.2 will flatten multi-dimensional arrays with a dot concatenation helper.

    if ( ! function_exists('array_dot'))
    {
    	/**
    	 * Flatten a multi-dimensional associative array with dots.
    	 *
    	 * @param  array   $array
    	 * @param  string  $prepend
    	 * @return array
    	 */
    	function array_dot($array, $prepend = '')
    	{
    		return Arr::dot($array, $prepend);
    	}
    }

**Comment by sballew** [comment]
Fixed in #11. Thanks for the pull.
